# 核心任务
- name: gogs
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml

  roles:
    - { role: role_common , tags: "role_common"}
    - { role: role_cloud , tags: "role_cloud"}
    - { role: role_nginx , tags: "role_nginx"}
    - { role: role_mysql , tags: "mysql"}
    - { role: role_docker , tags: "role_docker"}
    - { role: role_docker_phpmyadmin , tags: "role_docker_phpmyadmin"}
    - { role: gogs , tags: "gogs"}





    


                                                                                                    