- src: http://github.com/websoft9dev/role_common
  version: master

- src: http://github.com/websoft9dev/role_mysql
  version: master

- src: http://github.com/websoft9dev/role_docker
  version: master

- src: http://github.com/websoft9dev/role_nginx
  version: master

